on:
  push:
    branches:
      - main

name: Build

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for Git to git push
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Init
        run: python -m bioimageio_chatbot init
      - name: Test server
        run: |
        export OPENAI_API_KEY=sk-xxxxxxxx
        python -m bioimageio_chatbot start-server --host=0.0.0.0 --port=9000 & wget http://127.0.0.1:9000/public/apps/bioimageio-chatbot-client/index
      # - name: Build vector database
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     python -m bioimageio_chatbot create-knowledge-base --output-dir=./dist/bioimageio-knowledge-base
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_SECRET_API_KEY }}
      # - name: Deploy
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
